image: python:3.11

stages:
  - tests
  - lint

tests:
  stage: tests
  before_script:
    - apt-get -qq update
    - apt-get install make
  script:
    - make prepare-env
    - source venv/bin/activate
    - make test
  only:
    - test
